### ISSUE TITLE
Correct URL for data in README example - change csv to tsv

### ISSUE THREAD

**Issue by Sagitto** [EpistasisLab/scikit-rebate#26]
The URL for the data in the README example should point to

 'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.tsv.gz',  

not  'GAMETES_Epistasis_2-Way_20atts_0.4H_EDM-1_1.csv.gz'

**Comment by rhiever** [comment]
Fixed---thanks!
