### ISSUE TITLE
pip install currently installs version 4.0 instead of 5.0

### ISSUE THREAD

**Issue by ryanurbs** [EpistasisLab/scikit-rebate#40]
This was reported to me, but i haven't confirmed yet.

**Comment by rhiever** [comment]
Have you uploaded v5.0 to PyPi?

cc @weixuanfu

**Comment by ryanurbs** [comment]
No i haven't done this yet. Is this all we'd need to do to fix this issue?

**Comment by rhiever** [comment]
Yes. Check with @weixuanfu on the specifics.

**Comment by weixuanfu** [comment]
Updated!

https://pypi.org/project/skrebate/

#41 Please merge this PR to master branch since the format of email addresses for `setup` is changed.
