### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by ghost** [EpistasisLab/scikit-rebate#71]
---> 33 from skrebate import ReliefF
     34 import numpy as np
     35 from sklearn.linear_model import ARDRegression as ard

~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/skrebate/__init__.py in <module>
     26 
     27 from ._version import __version__
---> 28 from .relieff import ReliefF
     29 from .surf import SURF
     30 from .surfstar import SURFstar

~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/skrebate/relieff.py in <module>
     31 import sys
     32 from sklearn.base import BaseEstimator
---> 33 from sklearn.externals.joblib import Parallel, delayed
     34 from .scoring_utils import get_row_missing, ReliefF_compute_scores
     35 

ModuleNotFoundError: No module named 'sklearn.externals.joblib'

**Comment by wibeck** [comment]
have the same issue

**Comment by pseudoyim** [comment]
Looks like `scikit-learn` removed the `joblib` directory in v0.23.0 (it's [still there in v0.22.1](https://github.com/scikit-learn/scikit-learn/tree/0.22.1/sklearn/externals)). Installing `scikit-learn <0.23.0` resolved this issue for me.

**Comment by tanyanair** [comment]
There is an open PR to resolve this issue, and bring further updates to scikit-rebate but ti was opened on Feb 12. Would be great if the maintainers of this package merge the changes.
