### ISSUE TITLE
Release 0.62 does not correspond to commit 16798854 (master head)

### ISSUE THREAD

**Issue by arnaud-fossop** [EpistasisLab/scikit-rebate#77]
Hello,
My team is willing to use the latest commit in master branch (16798854e7fbca553416409be8f9ff6f71204dac). There is a release in PyPi (https://pypi.org/project/skrebate/0.62/#history) at the same date of this commit (Feb 15th, 2021). But this release does not contains the changes of this commit. For example the class `skrebate.TURF` is still `skrebate.TuRF`.

Please can you give more details on when this last commit will be released ?

Thanks a lot for your help.
Arnaud

**Comment by ryanurbs** [comment]
We are not sure why but despite submitting this release to PyPi it is not showing up as the default most recent installation.  To get around this just directly install the most recent version of skrebate using (pip install skrebate==0.7).  This should resolve the issue until we get around to the next release.

**Comment by arnaud-fossop** [comment]
Thanks a lot. You are totally right. I was mistaken because I used `skrebate>=0.7` but it still installed the 0.62 version.

Thanks for your rapid answer :).
